version: 2.1
jobs:
  install:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: "."
          paths:
            - "node_modules"

  test:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run: yarn test

  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run: yarn build

  
  deploy:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run: ls build

workflows:
  test_build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
