version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: 'circleci/node:lastest'
    steps:
      - checkout
      - run: yarn test
